---
title: Aurora Perez
description: Catálogo en internet de Aurora Perez - Argentina.
baseurl: "/girasol" # the subpath of your site, e.g. /blog
url: "http://tinchodias.github.io" # the base hostname & protocol for your site

facebook_username: "AuroraPerezArgentina"
pinterest_username: "auroraperezarg"
instagram_username: "auroraperezindumentaria"

collections:
  products:
    output: true
    permalink: /prendas/:path/

defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: product

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - bower.json
  - LICENSE.md
  - Rakefile
  - README.md
  - vendor/bundle
  - test
  - tests
  - assets/vendor/selectivizr/tests
  - jekyll.sublime-project
  - jekyll.sublime-workspace

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag

sass:
    sass_dir: _sass
    style: :compressed

