---
title: Aurora Perez
description: Catálogo en internet de Aurora Perez - Argentina.
relative_permalinks: false
markdown: kramdown

collections:
  products:
    output: true
    permalink: /products/:path/

defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: default

exclude:
  - Gemfile
  - Gemfile.lock
  - bower.json
  - LICENSE.md
  - Rakefile
  - README.md
  - script
  - vendor/bundle
  - test
  - tests
  - assets/vendor/selectivizr/tests

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag

sass:
    sass_dir: _sass
    style: :compressed

twitter:
  username: "@auroraperezarg"
