# Each product has YAML front matter describing the product's properties.
# The available fields are:

- name: title
  description: The SPDX-compliant, human-readable product name
  required: true

- name: source
  description: The URL to the product source text
  required: true

- name: description
  description: A human-readable description of the product
  required: true

- name: how
  description: Instructions on how to implement the product
  required: true

- name: conditions
  description: Bulleted list of required rules
  required: true

- name: permissions
  description: Bulleted list of permitted rules
  required: true

- name: limitations
  description: Bulleted list of limited rules
  required: true

# Optional fields

- name: note
  description: Additional information about the products
  required: false

- name: using
  description: 'A list of notable projects using the product in the form of `project_name: "url"`'
  required: false

- name: redirect_from
  description: Relative path(s) to redirect to the product from, to prevent breaking old URLs
  required: false

- name: nickname
  description: A shorter, human-readable product name where the SPDX product name (`title` above) is long
  required: false
